server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/crmAuthorDb
    username: postgres
    password: N.naveen@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka